sudo: false
language: python
cache: pip
before_script:
- pip install tox

# test script
script:  tox
notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=flake8
