---
version: '2'
services:
    app:
        image: food_database_example:dev
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            PYTHONUNBUFFERED: 0
            APP_SECRET: "changemeplease"
            APP_TITLE: "API Docs"
        networks:
            - internal
networks:
    internal:
        driver: bridge
